# Generated by Django 6.0.2 on 2026-02-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOrderingAPI', '0002_rename_quanity_cart_quantity_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='order',
            name='menuitem',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
