# Generated by Django 6.0.2 on 2026-02-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOrderingAPI', '0003_remove_menuitem_feature_remove_order_menuitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
